package vn.prostylee.notification.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

import vn.prostylee.core.entity.AuditEntity;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * EmailTemplate generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "email_template")
public class EmailTemplate extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "email_template_seq", sequenceName = "email_template_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "email_template_seq")
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "title", length = 512)
	private String title;

	@Column(name = "content", length = 15000)
	private String content;

	@Column(name = "template_file", length = 512)
	private String templateFile;

	@Column(name = "type", length = 128)
	private String type;

}
