package vn.prostylee.notification.entity;
// Generated Jun 1, 2020, 11:38:05 PM by Hibernate Tools 5.2.12.Final

import vn.prostylee.auth.entity.Account;
import vn.prostylee.core.entity.AuditEntity;
import lombok.*;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Notification generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "notification")
public class Notification extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id")
	private Account account;

	@Column(name = "title", length = 128)
	private String title;

	@Column(name = "content", length = 512)
	private String content;

	@Column(name = "type")
	private Integer type;

	@Column(name = "additional_data", length = 2048)
	private String additionalData;

	@Column(name = "mark_as_read")
	private Boolean markAsRead;

}
