package vn.prostylee.notification.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.prostylee.core.entity.AuditEntity;

/**
 * Notification generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "notification")
public class Notification extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "template 5col", length = 512)
	private String template5col;

	@Column(name = "user_id")
	private Long userId;

	@Column(name = "title", length = 512)
	private String title;

	@Column(name = "content", length = 4096)
	private String content;

	@Column(name = "type", length = 128)
	private String type;

	@Column(name = "additional_data", length = 4096)
	private String additionalData;

	@Column(name = "mark_as_read")
	private Boolean markAsRead;

}
