package vn.prostylee.notification.entity;
// Generated Jun 1, 2020, 11:38:05 PM by Hibernate Tools 5.2.12.Final

import vn.prostylee.auth.entity.Account;
import vn.prostylee.core.entity.AuditEntity;
import lombok.*;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * PushNotificationToken generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "push_notification_token", uniqueConstraints = @UniqueConstraint(columnNames = {"token"}))
public class PushNotificationToken extends AuditEntity {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @EqualsAndHashCode.Exclude
    @ToString.Exclude
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "account_id")
    private Account account;

    @Column(name = "token", length = 512, nullable = false, unique = true)
    private String token;

    @Column(name = "device_name", length = 128)
    private String deviceName;

    @Column(name = "device_id", length = 128)
    private String deviceId;

    @Column(name = "software", length = 128)
    private String software;

    @Column(name = "os_version", length = 128)
    private String osVersion;

    @Column(name = "os_name", length = 512)
    private String osName;

    @Column(name = "brand", length = 128)
    private String brand;

    @Column(name = "manufacturer", length = 128)
    private String manufacturer;

    @Column(name = "model_name", length = 128)
    private String modelName;
}
