package vn.prostylee.auth.entity;
// Generated Jun 28, 2020, 3:39:08 PM by Hibernate Tools 5.2.12.Final

import vn.prostylee.core.entity.AuditEntity;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Account generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "account_temp")
public class AccountTemp extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "username", nullable = false, length = 128)
	private String username;

	@Column(name = "password", nullable = false, length = 128)
	private String password;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expired_at", length = 19)
	private Date expiredAt;
}
