package vn.prostylee.auth.entity;
// Generated Jun 1, 2020, 11:38:05 PM by Hibernate Tools 5.2.12.Final

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.prostylee.core.entity.AuditEntity;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * AppClient generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "app_client")
public class AppClient extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "name", length = 128)
	private String name;

	@Column(name = "secret_key", length = 45)
	private String secretKey;

	@Column(name = "description", length = 512)
	private String description;

	@Column(name = "active")
	private Boolean active;

	@Column(name = "type", length = 128)
	private String type;

}
