package vn.prostylee.auth.entity;
// Generated Jun 28, 2020, 3:39:08 PM by Hibernate Tools 5.2.12.Final

import vn.prostylee.auth.entity.Role;
import vn.prostylee.core.entity.AuditEntity;
import lombok.*;

import javax.persistence.*;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Account generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "feature", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Feature extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "name", nullable = false, length = 128)
	private String name;

	@Column(name = "api_path", nullable = false, length = 128)
	private String apiPath;

	@Column(name = "code", nullable = false, length = 128)
	private String code;

	@Column(name = "group", nullable = false, length = 128)
	private String group;

	@Column(name = "order")
	private Integer order;

	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "feature_role", joinColumns = {
			@JoinColumn(name = "feature_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "role_id", nullable = false, updatable = false) })
	private Set<Role> roles;

}
