package vn.prostylee.auth.dto.response;

import lombok.Data;

/**
 * Role generated by hbm2java
 * @author prostylee
 */
@Data
public class RoleResponse {


	private Long id;
	private String name;
	private String code;
}
