package vn.prostylee.auth.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Role generated by hbm2java
 * @author prostylee
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class RoleResponse {


	private Long id;
	private String name;
	private String code;
}
