server:
  port: 8090
  servlet:
    contextPath: /api

app:
  security:
    allowed-origins:
      - "*"

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5433/prostylee
    username: postgres
    password: ENC(LIutR+3yZgTVvs2yu+IzPQ==)
  jpa:
    hibernate:
      ddl-auto: none
