server:
  port: 8090
  servlet:
    contextPath: /api

app:
  security:
    allowed-origins:
      - "*"

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    password: ENC(LIutR+3yZgTVvs2yu+IzPQ==)
    url: jdbc:log4jdbc:mysql://localhost:3306/prostylee?useUnicode=true&characterEncoding=utf8
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
