server:
  port: 8090
  servlet:
    contextPath: /api

app:
  security:
    allowed-origins:
      - "*"

spring:
  flyway:
    locations: db/migration,db/func
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://prostylee.csccjfkru4sa.ap-southeast-1.rds.amazonaws.com:5432/prostylee4dev
    username: postgres
    password: ENC(dMtpW4hsjR85/HRfyaYJRSxuY9Dziw/w1HtKjegRJwY=)
  jpa:
    hibernate:
      ddl-auto: none
