server:
  port: 8090
  servlet:
    contextPath: /api

app:
  security:
    allowed-origins:
      - "*"

    ## Scheduler using Spring Quartz
    ## Reference cron expression: https://crontab.guru/
    quartz:
      jobs:
        - # product-statistic
          detail:
            cron: '0 * 0/4 * * ?'
        - # store-statistic
          detail:
            cron: '0 * 0/4 * * ?'
        - # user-statistic
          detail:
            cron: '0 * 0/4 * * ?'
  StoreControllerIT
spring:
  flyway:
    locations: db/migration,db/func,db/masterdata,db/sampledata
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5433/prostylee
    username: postgres
    password: ENC(LIutR+3yZgTVvs2yu+IzPQ==)
  jpa:
    hibernate:
      ddl-auto: none
