version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db-dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: prostylee
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234567