version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db-dev
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: prostylee
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234567