version: '3'
services:
  postgres:
    image: postgres:12.5
    container_name: postgres-db-dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: prostylee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567