package vn.prostylee.useractivity.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import lombok.*;
import vn.prostylee.core.constant.TargetType;
import vn.prostylee.core.entity.AuditEntity;

import javax.persistence.*;
import java.util.Set;

/**
 * UserLike generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "user_rating")
public class UserRating extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "user_rating_seq", sequenceName = "user_rating_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_rating_seq")
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "target_id")
	private Long targetId;

	@Column(name = "target_type", length = 512)
	@Enumerated(EnumType.STRING)
	private TargetType targetType;

	@Column(name = "value")
	private Integer value;

	@Column(name = "content", length = 4096)
	private String content;

	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true, mappedBy = "userRating")
	private Set<UserRatingAttachment> attachments;

}
