package vn.prostylee.useractivity.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.prostylee.core.constant.TargetType;
import vn.prostylee.core.entity.AuditEntity;

import javax.persistence.*;

/**
 * UserStar generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "user_like")
public class UserLike extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "user_like_seq", sequenceName = "user_like_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_like_seq")
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "target_id")
	private Long targetId;

	@Column(name = "target_type", length = 512)
	@Enumerated(EnumType.STRING)
	private TargetType targetType;

	@Column(name = "custom_field_id_1")
	private Long customFieldId1;

	@Column(name = "custom_field_id_2")
	private Long customFieldId2;

	@Column(name = "custom_field_id_3")
	private Long customFieldId3;

}
