package vn.prostylee.product.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import lombok.*;
import vn.prostylee.core.entity.AuditEntity;

import javax.persistence.*;

/**
 * Category generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "category_relationship")
public class CategoryRelationship extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "category_relationship_seq", sequenceName = "category_relationship_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "category_relationship_seq")
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "category_id_1")
	private Long categoryId1;

	@Column(name = "category_id_2")
	private Long categoryId2;


}
