server:
  port: 8090
  servlet:
    contextPath: /api

app:
  security:
    allowed-origins:
      - "*"

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
