server:
  port: 8090
  servlet:
    contextPath: /api

app:
  security:
    allowed-origins:
      - "*"

spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  ## Config
  mail:
    host: localhost
    port: 2525
    username: test
    password: secret
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
        transport:
          protocol: smtp
    test-connection: false
