package vn.prostylee.voucher.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import lombok.*;
import vn.prostylee.core.entity.AuditEntity;

import javax.persistence.*;

/**
 * VoucherMasterData generated by hbm2java
 *
 * @author prostylee
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "voucher_master_data")
public class VoucherMasterData extends AuditEntity {

    private static final long serialVersionUID = 1L;

    @Id
    @SequenceGenerator(name = "voucher_master_data_seq", sequenceName = "voucher_master_data_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "voucher_master_data_seq")
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "group", length = 64)
    private String group;

    @Column(name = "name", length = 512)
    private String name;

    @Column(name = "key", length = 64)
    private String key;

    @Column(name = "description", length = 4096)
    private String description;

    @Column(name = "priority")
    private Integer priority;

    @Column(name = "active")
    private Boolean active;

}
