package vn.prostylee.voucher.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import lombok.*;
import vn.prostylee.core.entity.AuditEntity;

import javax.persistence.*;
import java.util.Date;

/**
 * VoucherUser generated by hbm2java
 *
 * @author prostylee
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "voucher_user")
public class VoucherUser extends AuditEntity {

    private static final long serialVersionUID = 1L;

    @Id
    @SequenceGenerator(name = "voucher_user_seq", sequenceName = "voucher_user_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "voucher_user_seq")
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "voucher_id")
    private Long voucherId;

    @Column(name = "voucher_code", length = 20)
    private String voucherCode;

    @Column(name = "store_id")
    private Long storeId;

    @Column(name = "order_id")
    private Long orderId;

    @Column(name = "used_at")
    private Date usedAt;

    @Column(name = "discount_amount")
    private Double discountAmount;

}
