package vn.prostylee.business.entity;
// Generated Jun 1, 2020, 11:38:05 PM by Hibernate Tools 5.2.12.Final

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.prostylee.core.entity.AuditEntity;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Image generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "image")
public class Image extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "original", length = 256)
	private String original;

	@Column(name = "display_name", length = 256)
	private String displayName;

	@Column(name = "thumbnail", length = 256)
	private String thumbnail;

}
