package vn.prostylee.order.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import vn.prostylee.core.entity.AuditEntity;

/**
 * Order generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "order")
public class Order extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "product_id", length = 512)
	private String productId;

	@Column(name = "code", length = 512)
	private String code;

	@Column(name = "price", length = 512)
	private String price;

	@Column(name = "product_price_id", length = 512)
	private String productPriceId;

	@Column(name = "status", length = 512)
	private String status;

	@Column(name = "shipping_type")
	private Long shippingType;

	@Column(name = "payment_type", length = 512)
	private String paymentType;

	@Column(name = "buyer_id", length = 512)
	private String buyerId;

	@Column(name = "seller_id")
	private Long sellerId;

	@Column(name = "store_id")
	private Long storeId;

	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	private Set<ShippingAddress> shippingAddresses;

}
