package vn.prostylee.order.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import lombok.*;
import vn.prostylee.core.entity.AuditEntity;
import vn.prostylee.payment.entity.PaymentType;
import vn.prostylee.shipping.entity.ShippingAddress;
import vn.prostylee.shipping.entity.ShippingProvider;

import javax.persistence.*;

/**
 * Order generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "order")
public class Order extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "order_seq", sequenceName = "order_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "order_seq")
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "code", length = 512)
	private String code;

	@Column(name = "total_money")
	private Double totalMoney;

	@Column(name = "status", length = 512)
	private String status;

	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@OneToOne
	@JoinColumn(name = "payment_type_id", nullable = false)
	private PaymentType paymentType;

	@Column(name = "buyer_id", length = 512)
	private String buyerId;

	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@OneToOne
	@JoinColumn(name = "shipping_address_id", nullable = false)
	private ShippingAddress shippingAddress;

	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@OneToOne
	@JoinColumn(name = "shipping_provider_id", nullable = false)
	private ShippingProvider shippingProvider;
}
