package vn.prostylee.order.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import lombok.*;
import vn.prostylee.core.entity.AuditEntity;
import vn.prostylee.product.entity.Product;
import vn.prostylee.store.entity.Store;

import javax.persistence.*;

/**
 * OrderDetail generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "order_detail")
public class OrderDetail extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "order_detail_seq", sequenceName = "order_detail_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "order_detail_seq")
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id", nullable = false)
	private Store store;

	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	private Product product;

	@Column(name = "product_price")
	private Double productPrice;

	@Column(name = "amount")
	private Integer amount;

	@Column(name = "product_name", length = 512)
	private String productName;

	@Column(name = "product_image", length = 512)
	private String productImage;

	@Column(name = "product_color", length = 512)
	private String productColor;

	@Column(name = "productproduct_size_size", length = 512)
	private String productSize;

	@Column(name = "product_data", length = 512)
	private String productData;

	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	private Order order;
}
