package vn.prostylee.order.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import lombok.*;
import vn.prostylee.core.entity.AuditEntity;

import javax.persistence.*;

/**
 * OrderDetailAttribute generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "order_detail_attribute")
public class OrderDetailAttribute extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "order_detail_attribute_seq", sequenceName = "order_detail_attribute_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "order_detail_attribute_seq")
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "key", length = 512)
	private String key;

	@Column(name = "label", length = 512)
	private String label;

	@Column(name = "value", length = 512)
	private String value;

	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_detail_id", nullable = false)
	private OrderDetail orderDetail;
}
