package vn.prostylee.order.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import vn.prostylee.core.entity.AuditEntity;

/**
 * ShippingAddress generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "shipping_address", catalog = "prostylee")
public class ShippingAddress extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	private Order order;

	@Column(name = "fullname", length = 512)
	private String fullname;

	@Column(name = "email", length = 512)
	private String email;

	@Column(name = "phone_number", length = 512)
	private String phoneNumber;

	@Column(name = "address1", length = 512)
	private String address1;

	@Column(name = "address2", length = 512)
	private String address2;

	@Column(name = "state", length = 512)
	private String state;

	@Column(name = "city", length = 512)
	private String city;

	@Column(name = "country", length = 512)
	private String country;

	@Column(name = "zipcode", length = 512)
	private String zipcode;

}
