package vn.prostylee.comment.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.*;
import vn.prostylee.core.entity.AuditEntity;

/**
 * CommentImage generated by hbm2java
 * @author prostylee
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Builder
@Table(name = "comment_image")
public class CommentImage extends AuditEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "comment_image_seq", sequenceName = "comment_image_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "comment_image_seq")
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	/**
	 * @see <a href="https://stackoverflow.com/questions/3325387/infinite-recursion-with-jackson-json-and-hibernate-jpa-issue">Fix problem Infinite recursion</a>
	 * By using @JsonIgnore
	 */
	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comment_id", nullable = false)
	private Comment comment;

	@Column(name = "attachment_id")
	private Long attachmentId;

	@Column(name = "order")
	private Integer order;

}
