package vn.prostylee.shipping.entity;
// Generated Nov 28, 2020, 9:45:59 PM by Hibernate Tools 5.2.12.Final

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import vn.prostylee.core.entity.AuditEntity;

import javax.persistence.*;

/**
 * ShippingAddress generated by hbm2java
 *
 * @author prostylee
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "shipping_address")
public class ShippingAddress extends AuditEntity {

    private static final long serialVersionUID = 1L;

    @Id
    @SequenceGenerator(name = "shipping_address_seq", sequenceName = "shipping_address_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "shipping_address_seq")
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "fullname", length = 512)
    private String fullName;

    @Column(name = "email", length = 512)
    private String email;

    @Column(name = "phone_number", length = 512)
    private String phoneNumber;

    @Column(name = "address1", length = 512)
    private String address1;

    @Column(name = "address2", length = 512)
    private String address2;

    @Column(name = "state", length = 512)
    private String state;

	@Column(name = "city", length = 512)
	private String city;

	@Column(name = "country", length = 512)
	private String country;

	@Column(name = "zipcode", length = 512)
	private String zipcode;
}
